import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar/Navbar";
import Siderbar from "@/Components/Sidebar/Siderbar";
import Footerbar from "@/Components/Footerbar/Footerbar";
import "bootstrap/dist/css/bootstrap.min.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body id="app">
   
          <div id="content">{children}</div>
    
      </body>
    </html>
  );
}
